spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cart
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8089

logging:
  level:
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
    org.hibernate.engine.transaction: INFO
    org.hibernate.engine.transaction.internal: INFO
    org.hibernate.stat: INFO
