INSERT INTO products (name, price, prod_type, prod_info, brand) VALUES
('Iphone 13', 699.99, 'Electronics', 'Latest smartphone with cutting-edge features', 'Apple'),
('Macbook Pro', 1299.99, 'Electronics', 'High-performance laptop for professionals', 'Apple'),
('Apple Watch Series 9', 199.99, 'Electronics', 'Advanced smartwatch with health tracking', 'Apple'),
('Samsung 4K Ultra HD TV', 899.99, 'Electronics', 'Ultra HD 4K television with HDR support', 'Samsung'),
('JBL Bluetooth Speaker', 49.99, 'Electronics', 'Portable Bluetooth speaker with excellent sound quality', 'JBL'),
('Adidas Pro Running Shoes', 89.99, 'Fashion', 'Comfortable running shoes with great cushioning', 'Adidas'),
('Classic Leather Jacket', 199.99, 'Fashion', 'Stylish leather jacket for a classic look', 'UrbanWear'),
('Comfort Jeans', 59.99, 'Fashion', 'Durable and comfortable jeans', 'DenimCo'),
('Graphic T-Shirt', 19.99, 'Fashion', 'Casual t-shirt with various designs', 'TeesGalore'),
('Aviator Sunglasses', 29.99, 'Fashion', 'Fashionable sunglasses with UV protection', 'ShadeMasters'),
('Mint Dental Floss', 4.99, 'Dental', 'Mint-flavored dental floss for daily use', 'SmileCare'),
('Electric Toothbrush', 49.99, 'Dental', 'Rechargeable electric toothbrush with multiple modes', 'CleanTeeth'),
('Whitening Toothpaste', 3.99, 'Dental', 'Toothpaste with whitening and cavity protection', 'BrightSmile'),
('Orthopedic Shoes', 129.99, 'Shoes', 'Shoes designed for orthopedic comfort', 'HealthStep'),
('Running Sneakers', 79.99, 'Shoes', 'Lightweight running sneakers', 'SpeedRunner'),
('Winter Boots', 99.99, 'Shoes', 'Warm and waterproof winter boots', 'MountainGear'),
('Leather Dress Shoes', 149.99, 'Shoes', 'Elegant leather dress shoes', 'FormalFeet'),
('Casual Slip-Ons', 49.99, 'Shoes', 'Comfortable casual slip-on shoes', 'EasyWear'),
('Noise Cancelling Headphones', 199.99, 'Electronics', 'Over-ear headphones with active noise cancellation', 'AudioPro'),
('Fitness Tracker', 59.99, 'Electronics', 'Wearable fitness tracker with heart rate monitor', 'FitTech'),
('Wireless Earbuds', 129.99, 'Electronics', 'True wireless earbuds with high-fidelity sound', 'SoundWave'),
('Gaming Laptop', 1599.99, 'Electronics', 'High-end gaming laptop with powerful graphics', 'GameMaster'),
('Digital Camera', 499.99, 'Electronics', 'DSLR camera with interchangeable lenses', 'PhotoGenix'),
('Designer Handbag', 249.99, 'Fashion', 'Luxury handbag with premium materials', 'StyleIcon'),
('Sports Jacket', 129.99, 'Fashion', 'Lightweight and waterproof sports jacket', 'ActiveWear'),
('Casual Sneakers', 39.99, 'Fashion', 'Everyday casual sneakers', 'ComfyFeet'),
('Dress Shirt', 34.99, 'Fashion', 'Formal dress shirt with a tailored fit', 'ShirtWorks'),
('Fashion Scarf', 14.99, 'Fashion', 'Elegant scarf for a stylish look', 'TrendSetter'),
('Electric Flosser', 69.99, 'Dental', 'Electric flosser for easy and effective flossing', 'FlossTech'),
('Mouthwash', 6.99, 'Dental', 'Antibacterial mouthwash for fresh breath', 'FreshMouth'),
('Toothbrush Set', 7.99, 'Dental', 'Set of manual toothbrushes', 'CleanTeeth'),
('Casual Loafers', 59.99, 'Shoes', 'Comfortable loafers for casual wear', 'EasyWear'),
('Hiking Boots', 139.99, 'Shoes', 'Durable hiking boots with great traction', 'TrailBlazer'),
('Running Shorts', 24.99, 'Fashion', 'Lightweight running shorts', 'ActiveWear'),
('Yoga Pants', 34.99, 'Fashion', 'Comfortable and flexible yoga pants', 'FitFlex'),
('Wireless Charger', 29.99, 'Electronics', 'Fast wireless charging pad', 'ChargePro'),
('Bluetooth Headset', 79.99, 'Electronics', 'Wireless headset with noise cancellation', 'AudioPro'),
('Fitness Watch', 99.99, 'Electronics', 'Smartwatch with fitness tracking features', 'FitTech'),
('Gaming Console', 399.99, 'Electronics', 'Next-gen gaming console with 4K support', 'GameMaster'),
('Portable SSD', 149.99, 'Electronics', 'High-speed portable solid-state drive', 'DataSafe'),
('Luxury Watch', 999.99, 'Fashion', 'High-end watch with premium materials', 'TimeKeeper'),
('Sports Shoes', 89.99, 'Fashion', 'Shoes designed for sports activities', 'ActiveWear'),
('Denim Jacket', 79.99, 'Fashion', 'Classic denim jacket', 'UrbanWear'),
('Cotton Shirt', 24.99, 'Fashion', 'Comfortable cotton shirt', 'ComfortWear'),
('Winter Coat', 199.99, 'Fashion', 'Warm and stylish winter coat', 'ColdGuard'),
('Dental Kit', 19.99, 'Dental', 'Complete dental care kit', 'SmileCare'),
('Toothbrush Holder', 9.99, 'Dental', 'Hygienic toothbrush holder', 'CleanTeeth'),
('Whitening Strips', 29.99, 'Dental', 'Teeth whitening strips for a brighter smile', 'BrightSmile'),
('Work Boots', 119.99, 'Shoes', 'Durable work boots with steel toes', 'HeavyDuty'),
('Leather Belt', 39.99, 'Fashion', 'Stylish leather belt', 'BeltCo'),
('Silk Tie', 24.99, 'Fashion', 'Elegant silk tie', 'TieMaster'),
('Waterproof Jacket', 149.99, 'Fashion', 'Jacket with waterproof fabric', 'WeatherGuard'),
('Bluetooth Mouse', 29.99, 'Electronics', 'Wireless mouse with Bluetooth connectivity', 'GadgetPro'),
('4K Monitor', 399.99, 'Electronics', 'Ultra HD monitor with stunning clarity', 'ViewMaster'),
('Portable Power Bank', 49.99, 'Electronics', 'High-capacity power bank', 'ChargePro'),
('Smart Light Bulbs', 39.99, 'Electronics', 'Smart LED bulbs with app control', 'BrightHome'),
('Robot Vacuum', 299.99, 'Electronics', 'Automatic vacuum cleaner with smart navigation', 'CleanBot'),
('Designer Sunglasses', 149.99, 'Fashion', 'Luxury sunglasses with UV protection', 'ShadeMasters'),
('Leather Wallet', 49.99, 'Fashion', 'Premium leather wallet', 'WalletWorks'),
('Winter Gloves', 24.99, 'Fashion', 'Warm gloves for winter', 'ColdGuard'),
('Fashion Hat', 19.99, 'Fashion', 'Stylish hat for all seasons', 'TrendSetter'),
('Electric Shaver', 89.99, 'Electronics', 'Rechargeable electric shaver', 'ShavePro'),
('Smart Home Hub', 99.99, 'Electronics', 'Central hub for smart home devices', 'HomeSmart'),
('Noise Reducing Earplugs', 14.99, 'Electronics', 'Comfortable earplugs for noise reduction', 'QuietComfort'),
('Fitness Band', 49.99, 'Electronics', 'Fitness band with activity tracking', 'FitTech'),
('Gaming Mouse', 59.99, 'Electronics', 'High-precision gaming mouse', 'GameMaster'),
('Ergonomic Keyboard', 79.99, 'Electronics', 'Comfortable ergonomic keyboard', 'TypeEase'),
('Home Security Camera', 129.99, 'Electronics', 'Wireless security camera with night vision', 'SafeHome'),
('Instant Camera', 69.99, 'Electronics', 'Instant camera for quick photo printing', 'PhotoSnap'),
('Noise Cancelling Earbuds', 149.99, 'Electronics', 'Earbuds with active noise cancellation', 'AudioPro'),
('Designer Sneakers', 199.99, 'Fashion', 'High-end designer sneakers', 'LuxuryFoot'),
('Fashionable Watch', 299.99, 'Fashion', 'Stylish watch with premium materials', 'TimeKeeper'),
('Casual Backpack', 49.99, 'Fashion', 'Durable backpack for everyday use', 'PackPro'),
('Cotton Sweater', 34.99, 'Fashion', 'Comfortable cotton sweater', 'CozyWear'),
('Travel Bag', 89.99, 'Fashion', 'Spacious travel bag with multiple compartments', 'Traveler'),
('Children’s Toothbrush', 4.99, 'Dental', 'Soft toothbrush for kids', 'SmileCare'),
('Anti-Cavity Toothpaste', 2.99, 'Dental', 'Toothpaste with anti-cavity formula', 'CleanTeeth'),
('Dental Mouth Guard', 19.99, 'Dental', 'Protective mouth guard for teeth', 'GuardSmile'),
('Running Tights', 29.99, 'Fashion', 'Flexible running tights', 'FitFlex'),
('Casual Slippers', 24.99, 'Shoes', 'Comfortable slippers for home', 'ComfyFeet'),
('Hiking Backpack', 119.99, 'Fashion', 'Durable hiking backpack with multiple pockets', 'TrailBlazer'),
('Leather Gloves', 39.99, 'Fashion', 'Elegant leather gloves', 'LuxuryHand'),
('Wireless Keyboard', 49.99, 'Electronics', 'Wireless keyboard with long battery life', 'TypeEase'),
('Smart Thermostat', 199.99, 'Electronics', 'Smart thermostat with app control', 'ClimateControl'),
('Portable Speaker', 89.99, 'Electronics', 'High-quality portable speaker', 'SoundWave'),
('Smart Doorbell', 149.99, 'Electronics', 'Doorbell with camera and app alerts', 'HomeSafe'),
('Noise Cancelling Headset', 199.99, 'Electronics', 'Headset with active noise cancellation', 'AudioPro'),
('Luxury Handbag', 349.99, 'Fashion', 'Designer handbag with premium materials', 'StyleIcon'),
('Wool Coat', 199.99, 'Fashion', 'Warm wool coat for winter', 'ColdGuard'),
('Fashionable Boots', 139.99, 'Shoes', 'Stylish boots for all seasons', 'TrendFoot'),
('Electric Kettle', 49.99, 'Electronics', 'Fast boiling electric kettle', 'KitchenPro'),
('Coffee Maker', 89.99, 'Electronics', 'Automatic coffee maker with programmable settings', 'BrewMaster'),
('Smartphone Stand', 14.99, 'Electronics', 'Adjustable stand for smartphones', 'GadgetPro'),
('Bluetooth Tracker', 29.99, 'Electronics', 'Tracker for finding lost items', 'FindIt'),
('Fitness Dumbbells', 49.99, 'Fitness', 'Set of adjustable dumbbells', 'FitGear'),
('Yoga Mat', 19.99, 'Fitness', 'Non-slip yoga mat', 'FitFlex'),
('Water Bottle', 14.99, 'Fitness', 'Reusable water bottle with filter', 'HydratePro'),
('Sports Bra', 29.99, 'Fashion', 'Supportive sports bra', 'ActiveWear'),
('Compression Socks', 19.99, 'Fashion', 'Socks with compression for better circulation', 'FitFeet');