INSERT INTO addresses (pin_code, city, state, country, street, locality, landmark, user_id, house_no) VALUES
('110001', 'New Delhi', 'Delhi', 'India', 'Connaught Place St', 'Connaught Place', 'Near Central Park', 4, '#14D'),
('400001', 'Mumbai', 'MH', 'India', 'Marine Drive St', 'Nariman Point', 'Near Marine Drive', 5, '#15E'),
('700001', 'Kolkata', 'WB', 'India', 'Park Street St', 'Park Street Area', 'Near Park Hotel', 6, '#16F'),
('600001', 'Chennai', 'TN', 'India', 'Mount Road St', 'Guindy', 'Near Guindy Park', 7, '#17G'),
('500001', 'Hyderabad', 'TS', 'India', 'Banjara Hills St', 'Banjara Hills', 'Near LV Prasad Eye Institute', 8, '#18H'),
('560001', 'Bangalore', 'KA', 'India', 'MG Road St', 'Brigade Road', 'Near Brigade Road', 9, '#19I'),
('380001', 'Ahmedabad', 'GJ', 'India', 'CG Road St', 'Navrangpura', 'Near HL College', 10, '#20J'),
('302001', 'Jaipur', 'RJ', 'India', 'MI Road St', 'Pink City Area', 'Near Hawa Mahal', 11, '#21K'),
('751001', 'Bhubaneswar', 'OR', 'India', 'Kharavela Nagar St', 'Kharavela Nagar', 'Near Railway Station', 12, '#22L'),
('144001', 'Jalandhar', 'PB', 'India', 'Model Town St', 'Model Town', 'Near Model Town Market', 13, '#23M'),
('160001', 'Chandigarh', 'CH', 'India', 'Sector 17 St', 'Sector 17', 'Near Sector 17 Market', 14, '#24N'),
('500081', 'Hyderabad', 'TS', 'India', 'Hitech City St', 'Hitech City', 'Near Cyber Towers', 15, '#25O'),
('171001', 'Shimla', 'HP', 'India', 'Mall Road St', 'Mall Road Area', 'Near Ridge', 16, '#26P'),
('682001', 'Kochi', 'KL', 'India', 'MG Road St', 'Ernakulam', 'Near Marine Drive', 17, '#27Q'),
('737101', 'Gangtok', 'SK', 'India', 'MG Marg St', 'MG Marg Area', 'Near Lal Bazaar', 18, '#28R'),
('793001', 'Shillong', 'ML', 'India', 'Police Bazar St', 'Police Bazar Area', 'Near Ward Lake', 19, '#29S'),
('492001', 'Raipur', 'CG', 'India', 'MG Road St', 'Pandri', 'Near City Center Mall', 20, '#30T'),
('440001', 'Nagpur', 'MH', 'India', 'Sitabuldi St', 'Sitabuldi Area', 'Near Empress Mall', 21, '#31U'),
('462001', 'Bhopal', 'MP', 'India', 'New Market St', 'New Market Area', 'Near TT Nagar Stadium', 22, '#32V'),
('226001', 'Lucknow', 'UP', 'India', 'Hazratganj St', 'Hazratganj', 'Near Sahara Ganj Mall', 23, '#33W'),
('700027', 'Kolkata', 'WB', 'India', 'Salt Lake St', 'Salt Lake Area', 'Near City Centre Mall', 24, '#34X'),
('110070', 'New Delhi', 'Delhi', 'India', 'Vasant Kunj St', 'Vasant Kunj', 'Near DLF Promenade', 25, '#35Y'),
('641001', 'Coimbatore', 'TN', 'India', 'Gandhipuram St', 'Gandhipuram', 'Near Town Hall', 26, '#36Z'),
('751024', 'Bhubaneswar', 'OR', 'India', 'Jayadev Vihar St', 'Jayadev Vihar', 'Near Fortune Tower', 3, '#37A'),
('713203', 'Durgapur', 'WB', 'India', 'City Centre St', 'City Centre', 'Near Junction Mall', 2, '#38B'),
('834001', 'Ranchi', 'JH', 'India', 'Main Road St', 'Main Road Area', 'Near GEL Church Complex', 1, '#39C');
